// import houseIcon from '../assets/Frame-2007.png'
import { RiRadioButtonLine } from 'react-icons/ri'
import { AiOutlineStop } from 'react-icons/ai'

export const landlordProperties = [
  {
    id: 2021,
    // image: houseIcon,
    icon: <AiOutlineStop/>,
    title: 'House of Elovia',
    location: 'Ikeja Road, Lagos State',
    tableData: [
      {
        id: 20211,
        no: '1.',
        bed: '3',
        tenantName: '-',
        name: 'Love',
        unitType: 'Flat',
        rentTerm: '-',
        status: 'Vacant',
        amt: '#1,000,000.00k',
      },
      {
        id: 20212,
        no: '2.',
        bed: '5',
        tenantName: 'Mr. Kelly',
        unitType: 'Self contain',
        name: 'Peace',
        rentTerm: '6 months',
        status: 'Occupied',
        amt: '#400,000.00k',
      },
      {
        id: 20213,
        no: '3.',
        bed: '2',
        name: 'Joy',
        tenantName: 'Mr. Segun',
        unitType: 'Bungalow',
        rentTerm: '6 months',
        status: 'Occupied',
        amt: '#400,000.00k',
      },
      {
        id: 20214,
        no: '4.',
        bed: '3',
        tenantName: '-',
        name: 'Grace',
        unitType: 'Bungalow',
        rentTerm: '-',
        status: 'Vacant',
        amt: '#1,000,000.00k',
      },
    ],
  },
  {
    id: 2022,
    // image: houseIcon,
    icon: <RiRadioButtonLine/>,
    title: 'House of Elovia',
    location: 'Ikeja Road, Lagos State',
    tableData: [
      {
        id: 20221,
        no: '1.',
        bed: '3',
        tenantName: '-',
        name: 'Love',
        unitType: 'Flat',
        rentTerm: '-',
        status: 'Vacant',
        amt: '#1,000,000.00k',
      },
      {
        id: 20222,
        no: '2.',
        name: 'Peace',
        bed: '5',
        tenantName: 'Mr. Kelly',
        unitType: 'Self contain',
        rentTerm: '6 months',
        status: 'Occupied',
        amt: '#400,000.00k',
      },
      {
        id: 20223,
        no: '3.',
        bed: '2',
        name: 'Joy',
        tenantName: 'Mr. Segun',
        unitType: 'Bungalow',
        rentTerm: '6 months',
        status: 'Occupied',
        amt: '#400,000.00k',
      },
      {
        id: 20224,
        no: '4.',
        bed: '3',
        name: 'Grace',
        tenantName: '-',
        unitType: 'Bungalow',
        rentTerm: '-',
        status: 'Vacant',
        amt: '#1,000,000.00k',
      },
    ],
  },
]